<a href="https://colab.research.google.com/github/beeradical/beeradical/blob/main/3DJPG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
!pip3 install numpy-stl



In [ ]:
Start Quick

Reading Image From File



In [5]:
from PIL import Image
import matplotlib.pyplot as plt
im = Image.open("/content/lucky.jpg") 
plt.imshow(im) 


convert to gray scale


In [40]:
grey_img = Image.open('/content/lucky.jpg').convert('LA')
plt.imshow(grey_img)

Surface
 made with triangles
**bold text**

In [24]:
import numpy as np
from stl import mesh

# Define the 8 vertices of the surface
vertices = np.array([\
    [-1, -1, -1],
    [+1, -1, -1],
    [+1, +1, -1],
    [-1, +1, -1],])
# Define the 2 triangles composing the surface
faces = np.array([\
    [1,2,3],
    [3,1,0],])

# Create the mesh
cube = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
        cube.vectors[i][j] = vertices[f[j],:]

# Write the mesh to file "cube.stl"
cube.save('surface.stl')





Create Surface 1000 x 1100 with N traiangles


In [55]:
print(grey_img.size)
(ncols,nrows)=grey_img.size

vertices=np.zeros((nrows,ncols,3))

for x in range(0, ncols):
  for y in range(0, nrows):
    z = 0 
    vertices[y][x]=(x, y, z)

faces=[]

for x in range(0,ncols-1):
  for y in range(0,nrows-1):
    z=0
    #create face1
    vertice1=vertices[y][x]
    vertice2=vertices[y+1][x]
    vertice3=vertices[y+1][x+1]


    face1=np.array([vertice1, vertice2, vertice3 ])
    
    #create face2
    vertice1=vertices[y][x]
    vertice2=vertices[y+1][x+1]
    vertice3=vertices[y+1][x+1]

    face2=np.array([vertice1, vertice2, vertice3])

    faces.append(face1)
    faces.append(face2)

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
#mesh creation
surface=mesh.Mesh(np.zeros(facesNp.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
  for j in range(3):
    surface.vectors[i][j]=facesNp[i][j]
#write mesh to file "cube.stl"
surface.save('surface.stl')
print(surface)


  

(828, 636)
number of faces: 1050290


In [45]:
a = np.zeros((3, 3))
a[:,0]=3

print(a)

[[3. 0. 0.]
 [3. 0. 0.]
 [3. 0. 0.]]
